using System;
using ExpenseHub.Api.Domain.Entities;

namespace ExpenseHub.Api.Expenses;

/// <summary>
/// Public representation of an expense.
/// </summary>
/// <param name="Id">The identifier generated by the server.</param>
/// <param name="OwnerId">The identifier of the owner, taken from the token when the expense was created.</param>
/// <param name="Description">The description.</param>
/// <param name="Amount">The single amount.</param>
/// <param name="ExpenseDate">The date the expense happened.</param>
/// <param name="Status">The current state, as text.</param>
/// <param name="CreatedAtUtc">The UTC instant the draft was created.</param>
public sealed record ExpenseResponse(
    Guid Id,
    string OwnerId,
    string Description,
    decimal Amount,
    DateOnly ExpenseDate,
    string Status,
    DateTimeOffset CreatedAtUtc)
{
    /// <summary>
    /// Builds the response of an expense.
    /// </summary>
    /// <param name="expense">The expense.</param>
    /// <returns>The public representation.</returns>
    public static ExpenseResponse From(Expense expense)
    {
        ArgumentNullException.ThrowIfNull(expense);

        return new ExpenseResponse(
            expense.Id,
            expense.OwnerId,
            expense.Description,
            expense.Amount,
            expense.ExpenseDate,
            expense.Status.ToString(),
            expense.CreatedAtUtc);
    }
}
