using System;
using System.Collections.Generic;
using ExpenseHub.Api.Domain.Enums;

namespace ExpenseHub.Api.Domain.Entities;

/// <summary>
/// A reimbursement request with a single amount.
/// </summary>
public class Expense
{
    /// <summary>Gets or sets the identifier generated by the server.</summary>
    public Guid Id { get; set; }

    /// <summary>Gets or sets the Identity user id of the owner, taken from the token.</summary>
    public string OwnerId { get; set; } = string.Empty;

    /// <summary>Gets or sets the description.</summary>
    public string Description { get; set; } = string.Empty;

    /// <summary>Gets or sets the single amount of the expense.</summary>
    public decimal Amount { get; set; }

    /// <summary>Gets or sets the date the expense happened.</summary>
    public DateOnly ExpenseDate { get; set; }

    /// <summary>Gets or sets the current state, set only by the server.</summary>
    public ExpenseStatus Status { get; set; }

    /// <summary>Gets or sets the UTC instant the draft was created.</summary>
    public DateTimeOffset CreatedAtUtc { get; set; }

    /// <summary>Gets the history entries of this expense.</summary>
    public ICollection<ExpenseHistory> History { get; } = [];

    /// <summary>Gets or sets the payment record, when the expense was paid.</summary>
    public PaymentRecord? Payment { get; set; }
}
