using System;
using System.Linq;
using System.Threading.Tasks;
using ExpenseHub.Api.Domain.Entities;
using ExpenseHub.Api.Domain.Enums;
using ExpenseHub.Api.Expenses;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace ExpenseHub.UnitTests.Expenses;

/// <summary>
/// Tests of the creation of drafts, using a fake repository and a fixed clock, with no database.
/// </summary>
[TestClass]
public sealed class ExpenseServiceCreateTests
{
    private const string Owner = "owner-1";

    /// <summary>A valid request creates a draft owned by the caller, with the data sent by the client.</summary>
    [TestMethod]
    public async Task CreateAsync_ValidData_CreatesADraftOwnedByTheCaller()
    {
        var repository = new FakeExpenseRepository();

        ExpenseOperationResult result = await NewService(repository).CreateAsync(ExpenseTestData.Employee(Owner), ExpenseTestData.Valid);

        Assert.AreEqual(ExpenseOperationStatus.Succeeded, result.Status);
        Assert.IsNotNull(result.Expense);
        Assert.AreEqual(ExpenseStatus.Draft, result.Expense.Status);
        Assert.AreEqual(Owner, result.Expense.OwnerId);
        Assert.AreEqual(ExpenseTestData.Valid.Description, result.Expense.Description);
        Assert.AreEqual(87.50m, result.Expense.Amount);
        Assert.AreEqual(new DateOnly(2026, 10, 1), result.Expense.ExpenseDate);
        Assert.AreEqual(1, repository.AddCalls);
    }

    /// <summary>The identifier and the creation instant are generated by the server.</summary>
    [TestMethod]
    public async Task CreateAsync_ValidData_GeneratesTheIdAndTheInstantOnTheServer()
    {
        var repository = new FakeExpenseRepository();

        ExpenseOperationResult result = await NewService(repository).CreateAsync(ExpenseTestData.Employee(Owner), ExpenseTestData.Valid);

        Assert.IsNotNull(result.Expense);
        Assert.AreNotEqual(Guid.Empty, result.Expense.Id);
        Assert.AreEqual(ExpenseTestData.Now, result.Expense.CreatedAtUtc);
        Assert.AreEqual(TimeSpan.Zero, result.Expense.CreatedAtUtc.Offset);
    }

    /// <summary>Two drafts never share an identifier.</summary>
    [TestMethod]
    public async Task CreateAsync_TwoDrafts_GetDifferentIds()
    {
        var repository = new FakeExpenseRepository();
        ExpenseService service = NewService(repository);

        ExpenseOperationResult first = await service.CreateAsync(ExpenseTestData.Employee(Owner), ExpenseTestData.Valid);
        ExpenseOperationResult second = await service.CreateAsync(ExpenseTestData.Employee(Owner), ExpenseTestData.Valid);

        Assert.AreNotEqual(first.Expense!.Id, second.Expense!.Id);
    }

    /// <summary>The creation is recorded in the history in the same save as the draft.</summary>
    [TestMethod]
    public async Task CreateAsync_ValidData_RecordsTheCreationInTheSameSave()
    {
        var repository = new FakeExpenseRepository();

        ExpenseOperationResult result = await NewService(repository).CreateAsync(ExpenseTestData.Employee(Owner), ExpenseTestData.Valid);

        Assert.AreEqual(1, repository.HistoryCountWhenAdded);
        ExpenseHistory entry = result.Expense!.History.Single();
        Assert.AreEqual(ExpenseHistoryAction.Created, entry.Action);
        Assert.AreEqual(Owner, entry.ActorId);
        Assert.AreEqual(ExpenseTestData.Now, entry.OccurredAtUtc);
        Assert.IsNull(entry.PreviousStatus);
        Assert.AreEqual(ExpenseStatus.Draft, entry.NewStatus);
    }

    /// <summary>Spaces around the description are not stored.</summary>
    [TestMethod]
    public async Task CreateAsync_DescriptionWithSpacesAtTheEnds_StoresItTrimmed()
    {
        var repository = new FakeExpenseRepository();
        var details = new ExpenseDetails("   Almoco com cliente em Campinas   ", 10m, ExpenseTestData.Today);

        ExpenseOperationResult result = await NewService(repository).CreateAsync(ExpenseTestData.Employee(Owner), details);

        Assert.AreEqual("Almoco com cliente em Campinas", result.Expense!.Description);
    }

    /// <summary>Invalid data is rejected and nothing is saved.</summary>
    /// <param name="description">The description.</param>
    /// <param name="amount">The amount, written with a dot, or an empty text for a missing amount.</param>
    /// <param name="daysFromToday">The date, as days after today.</param>
    /// <param name="invalidField">The field expected in the errors.</param>
    [TestMethod]
    [DataRow("curta", "10", 0, "Description")]
    [DataRow("   curta   ", "10", 0, "Description")]
    [DataRow("", "10", 0, "Description")]
    [DataRow(null, "10", 0, "Description")]
    [DataRow("Almoco com cliente em Campinas", "0", 0, "Amount")]
    [DataRow("Almoco com cliente em Campinas", "0.009", 0, "Amount")]
    [DataRow("Almoco com cliente em Campinas", "12.345", 0, "Amount")]
    [DataRow("Almoco com cliente em Campinas", "2147483647.01", 0, "Amount")]
    [DataRow("Almoco com cliente em Campinas", "-5", 0, "Amount")]
    [DataRow("Almoco com cliente em Campinas", "", 0, "Amount")]
    [DataRow("Almoco com cliente em Campinas", "10", 1, "ExpenseDate")]
    public async Task CreateAsync_InvalidData_IsRejectedAndSavesNothing(
        string? description,
        string amount,
        int daysFromToday,
        string invalidField)
    {
        var repository = new FakeExpenseRepository();
        decimal? parsedAmount = amount.Length == 0 ? null : ExpenseTestData.Dec(amount);
        var details = new ExpenseDetails(description, parsedAmount, ExpenseTestData.Today.AddDays(daysFromToday));

        ExpenseOperationResult result = await NewService(repository).CreateAsync(ExpenseTestData.Employee(Owner), details);

        Assert.AreEqual(ExpenseOperationStatus.ValidationFailed, result.Status);
        Assert.IsTrue(result.Errors.Any(error => error.Field == invalidField));
        Assert.AreEqual(0, repository.AddCalls);
        Assert.IsEmpty(repository.Expenses);
    }

    /// <summary>A description above 500 characters is rejected.</summary>
    [TestMethod]
    public async Task CreateAsync_DescriptionAbove500Characters_IsRejected()
    {
        var repository = new FakeExpenseRepository();
        var details = new ExpenseDetails(new string('a', 501), 10m, ExpenseTestData.Today);

        ExpenseOperationResult result = await NewService(repository).CreateAsync(ExpenseTestData.Employee(Owner), details);

        Assert.AreEqual(ExpenseOperationStatus.ValidationFailed, result.Status);
        Assert.AreEqual(0, repository.AddCalls);
    }

    /// <summary>A missing date is rejected.</summary>
    [TestMethod]
    public async Task CreateAsync_MissingDate_IsRejected()
    {
        var repository = new FakeExpenseRepository();
        var details = new ExpenseDetails(ExpenseTestData.Valid.Description, 10m, null);

        ExpenseOperationResult result = await NewService(repository).CreateAsync(ExpenseTestData.Employee(Owner), details);

        Assert.AreEqual(ExpenseOperationStatus.ValidationFailed, result.Status);
        Assert.AreEqual(0, repository.AddCalls);
    }

    /// <summary>The limits of the contract are accepted: 10 and 500 characters, 0.01 and Int32.MaxValue, today.</summary>
    /// <param name="descriptionLength">The length of the description.</param>
    /// <param name="amount">The amount, written with a dot.</param>
    [TestMethod]
    [DataRow(10, "0.01")]
    [DataRow(500, "2147483647")]
    [DataRow(500, "2147483647.00")]
    public async Task CreateAsync_DataOnTheLimits_IsAccepted(int descriptionLength, string amount)
    {
        var repository = new FakeExpenseRepository();
        var details = new ExpenseDetails(new string('a', descriptionLength), ExpenseTestData.Dec(amount), ExpenseTestData.Today);

        ExpenseOperationResult result = await NewService(repository).CreateAsync(ExpenseTestData.Employee(Owner), details);

        Assert.AreEqual(ExpenseOperationStatus.Succeeded, result.Status);
        Assert.AreEqual(1, repository.AddCalls);
    }

    /// <summary>Several invalid fields are all reported together.</summary>
    [TestMethod]
    public async Task CreateAsync_SeveralInvalidFields_ReportsAllOfThem()
    {
        var repository = new FakeExpenseRepository();
        var details = new ExpenseDetails("curta", 0m, ExpenseTestData.Today.AddDays(2));

        ExpenseOperationResult result = await NewService(repository).CreateAsync(ExpenseTestData.Employee(Owner), details);

        Assert.HasCount(3, result.Errors);
    }

    /// <summary>The date rule uses today's date in Brasilia time: at 23:30 there the UTC date is already tomorrow, but the day is not.</summary>
    [TestMethod]
    public async Task CreateAsync_NearMidnightInBrasilia_UsesTheBrazilianDate()
    {
        var repository = new FakeExpenseRepository();
        var lateEvening = new DateTimeOffset(2026, 10, 3, 2, 30, 0, TimeSpan.Zero);
        ExpenseService service = new(repository, new FixedTimeProvider(lateEvening));

        ExpenseOperationResult today = await service.CreateAsync(ExpenseTestData.Employee(Owner), new ExpenseDetails(ExpenseTestData.Valid.Description, 10m, new DateOnly(2026, 10, 2)));
        ExpenseOperationResult utcToday = await service.CreateAsync(ExpenseTestData.Employee(Owner), new ExpenseDetails(ExpenseTestData.Valid.Description, 10m, new DateOnly(2026, 10, 3)));

        Assert.AreEqual(ExpenseOperationStatus.Succeeded, today.Status);
        Assert.AreEqual(ExpenseOperationStatus.ValidationFailed, utcToday.Status);
    }

    /// <summary>The service itself requires the Employee role: without it nothing is created, whatever the attribute of the endpoint says.</summary>
    /// <param name="roles">The roles of the user, separated by comma; empty for none.</param>
    [TestMethod]
    [DataRow("Approver")]
    [DataRow("Finance")]
    [DataRow("Auditor")]
    [DataRow("Admin")]
    [DataRow("Approver,Finance")]
    [DataRow("")]
    public async Task CreateAsync_CallerWithoutTheEmployeeRole_IsForbiddenAndSavesNothing(string roles)
    {
        var repository = new FakeExpenseRepository();
        ExpenseCaller caller = ExpenseTestData.Caller(Owner, roles.Length == 0 ? [] : roles.Split(','));

        ExpenseOperationResult result = await NewService(repository).CreateAsync(caller, ExpenseTestData.Valid);

        Assert.AreEqual(ExpenseOperationStatus.Forbidden, result.Status);
        Assert.AreEqual(0, repository.AddCalls);
        Assert.IsEmpty(repository.Expenses);
    }

    /// <summary>The missing role is reported before the validation: a user who cannot create learns nothing about the data rules.</summary>
    [TestMethod]
    public async Task CreateAsync_WithoutTheRoleAndWithInvalidData_IsForbiddenNotInvalid()
    {
        var repository = new FakeExpenseRepository();
        var invalid = new ExpenseDetails("curta", 0m, ExpenseTestData.Today.AddDays(1));

        ExpenseOperationResult result = await NewService(repository).CreateAsync(ExpenseTestData.Caller(Owner, "Auditor"), invalid);

        Assert.AreEqual(ExpenseOperationStatus.Forbidden, result.Status);
    }

    /// <summary>Other roles do not stop an Employee from creating: roles accumulate.</summary>
    [TestMethod]
    public async Task CreateAsync_EmployeeWhoIsAlsoAuditor_CreatesTheDraft()
    {
        var repository = new FakeExpenseRepository();

        ExpenseOperationResult result = await NewService(repository).CreateAsync(ExpenseTestData.Caller(Owner, "Employee", "Auditor"), ExpenseTestData.Valid);

        Assert.AreEqual(ExpenseOperationStatus.Succeeded, result.Status);
        Assert.AreEqual(Owner, result.Expense!.OwnerId);
    }

    /// <summary>A caller without an identifier cannot create a draft.</summary>
    /// <param name="ownerId">An owner that is missing or blank.</param>
    [TestMethod]
    [DataRow(null)]
    [DataRow("")]
    [DataRow("  ")]
    public async Task CreateAsync_CallerWithoutIdentifier_Throws(string? ownerId)
    {
        var repository = new FakeExpenseRepository();

        await Assert.ThrowsAsync<ArgumentException>(() => NewService(repository).CreateAsync(ExpenseTestData.Employee(ownerId!), ExpenseTestData.Valid));

        Assert.AreEqual(0, repository.AddCalls);
    }

    private static ExpenseService NewService(FakeExpenseRepository repository)
    {
        return new ExpenseService(repository, new FixedTimeProvider(ExpenseTestData.Now));
    }
}
